### ISSUE TITLE
Refactor code introduced with Pull Request #1

### ISSUE THREAD

**Issue by jswindell** [jswindell/CascadingSelectsDemo#2]
@stashukny has blessed this repo with a contribution implementing the third drop-down with console games based on the previously selected  Developer. Good job!

However, the code submitted could be better and should be!

Please refactor the code introduced into https://github.com/jswindell/CascadingSelectsDemo/pull/1 from a peer review detailed herein.

**Comment by jswindell** [comment]
Here are my comments, if you care to get started:

**Web API routes are better understood when [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer)**
- In this case, the Developer is the main resource with supporting Consoles and Console Games.
- I think the following fits better:

`
developer/{developer}/consoles/{console}
`

**The "GameSystemController" should only contain public method a user can interact with:**

``` csharp
 private string[] SelectGames(string developer, string console)
```
- This should go in a helper class or something.

What do you think?

**Comment by stashukny** [comment]
Makes sense, thanks.
